# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - build
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race
